# Generated by Django 6.0.4 on 2026-04-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='首页首屏背景图，建议使用浅色或留白较多的横向图片。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
