# Generated by Django 6.0.4 on 2026-04-21 01:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_appear_in_search_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_quick_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '首屏快捷入口展示图，前台将按固定尺寸居中裁剪。', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link', 0), ('title', 1), ('image', 2)]], {})}, help_text='显示在首页首屏标题下方，建议添加 2 到 4 个外部链接，并为每个入口上传一张图片。', verbose_name='首屏快捷入口'),
        ),
    ]
