# Generated by Django 6.0.4 on 2026-06-10 03:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_hero_quick_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 4), ('html', 5), ('cta', 15), ('statistics', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'components/streamfield/blocks/heading2_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3'], 'template': 'components/streamfield/blocks/paragraph_block.html'}), 2: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '用于导入或嵌入受信任来源的 HTML。普通正文请使用段落。', 'label': 'HTML'}), 3: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('html', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 3)]], {}), 5: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '用于导入或嵌入受信任来源的 HTML。普通正文请使用章节和段落。', 'label': 'HTML'}), 6: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'required': True}), 7: ('wagtail.blocks.PageChooserBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': '留空时使用页面的列表标题。', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('page', 7), ('title', 8)]], {}), 10: ('wagtail.blocks.URLBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('link', 10), ('title', 11)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('internal', 9), ('external', 12)]], {}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('heading', 6), ('link', 13), ('description', 14)]], {}), 16: ('wagtail.blocks.BooleanBlock', (), {'help_text': '勾选后标题仅对屏幕阅读器可见。', 'label': '仅屏幕阅读器显示', 'required': False}), 17: ('wagtail.snippets.blocks.SnippetChooserBlock', ('utils.Statistic',), {}), 18: ('wagtail.blocks.ListBlock', (17,), {'max_num': 3, 'min_num': 3}), 19: ('wagtail.blocks.StructBlock', [[('heading', 6), ('sr_only_label', 16), ('statistics', 18)]], {})}),
        ),
    ]
