# Generated by Django 6.0.4 on 2026-04-20 09:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmessagessettings',
            options={'verbose_name': '系统提示'},
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='default_sharing_text',
            field=models.CharField(blank=True, help_text='当页面未单独设置分享文案时使用此默认值。', max_length=255, verbose_name='默认分享文案'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, help_text='填写 Facebook 应用 ID。', max_length=255, verbose_name='Facebook 应用 ID'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='填写 Instagram 用户名。', max_length=255, verbose_name='Instagram 用户名'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin_handle',
            field=models.CharField(blank=True, help_text='填写 LinkedIn 账号名称。', max_length=255, verbose_name='LinkedIn 账号'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='tiktok_handle',
            field=models.CharField(blank=True, help_text='填写 TikTok 用户名。', max_length=255, verbose_name='TikTok 用户名'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='填写不含 @ 的 Twitter 用户名。', max_length=255, verbose_name='Twitter 用户名'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='body_404',
            field=wagtail.fields.RichTextField(default='<p>你访问的页面可能不存在，或已经被移动。</p>', verbose_name='404 文本'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='footer_newsletter_signup_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='页脚说明文字'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='footer_newsletter_signup_link',
            field=models.URLField(blank=True, help_text='页脚按钮跳转链接；留空则不显示该按钮。', null=True, verbose_name='页脚跳转链接'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='footer_newsletter_signup_title',
            field=models.CharField(default='订阅通讯', max_length=120, verbose_name='页脚按钮标题'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='placeholder_image',
            field=models.ForeignKey(help_text='默认展示的占位图片。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='默认占位图'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='title_404',
            field=models.CharField(default='页面未找到', max_length=255, verbose_name='404 标题'),
        ),
    ]
