# Generated by Django 6.0.4 on 2026-04-20 09:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='action_text',
            field=models.CharField(blank=True, help_text='表单按钮文字；留空时默认为“提交”。', max_length=32, verbose_name='提交按钮文字'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='appear_in_search_results',
            field=models.BooleanField(default=True, help_text='勾选后允许搜索引擎收录该页面；取消勾选后将不再建议搜索引擎索引。', verbose_name='允许搜索引擎收录'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='listing_image',
            field=models.ForeignKey(blank=True, help_text='该页面出现在列表中时使用的展示图片。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='列表图片'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='listing_summary',
            field=models.CharField(blank=True, help_text='该页面出现在列表中时使用的摘要；如果上方未填写 Meta 描述，也会作为搜索引擎描述使用。', max_length=255, verbose_name='列表摘要'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='listing_title',
            field=models.CharField(blank=True, help_text='用于覆盖列表中显示的页面标题。', max_length=255, verbose_name='列表标题'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='社交分享图片'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='social_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='社交分享文案'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='提交成功提示'),
        ),
    ]
