# Generated by Django 6.0.4 on 2026-04-20 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('standardpages', '0003_bootstrap_lab_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyindexpage',
            name='default_photo',
            field=models.ForeignKey(blank=True, help_text='成员未上传头像时使用的默认占位图。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
