# Generated by Django 6.0.4 on 2026-05-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardpages', '0005_alter_achievementindexpage_appear_in_search_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypage',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='facultypage',
            name='faculty_group',
            field=models.CharField(blank=True, choices=[('infectious-complications', '感染性疾病并发症机制及新药研发'), ('antimicrobial-resistance', '细菌耐药机制及新药研发'), ('emerging-viral-pathogenesis', '新冠病毒等突发性病毒致病机制'), ('persistent-viral-pathogenesis', '持续性病毒致病机制及新药研发')], default='', max_length=32, verbose_name='人员分类'),
        ),
    ]
