# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0012_add_technology_transfer_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultypage",
            name="official_profile_url",
            field=models.URLField(
                blank=True,
                help_text="填写后，师资列表中的姓名会直接打开该官网介绍页。",
                verbose_name="官网介绍链接",
            ),
        ),
    ]
