# Generated by Django 6.0.4 on 2026-04-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_logo',
            field=models.ForeignKey(blank=True, help_text='Header logo image. If empty, the built-in SKL logo is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_subtitle',
            field=models.CharField(blank=True, help_text='Optional second line under the brand title.', max_length=160),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_title',
            field=models.CharField(blank=True, help_text='Header brand title. If empty, the Wagtail site name is used.', max_length=120),
        ),
    ]
