# Generated by Codex on 2026-04-20

from django.db import migrations, models


def split_existing_brand_title(apps, schema_editor):
    NavigationSettings = apps.get_model("navigation", "NavigationSettings")
    NavigationSettings.objects.filter(
        brand_title="抗感染新药研发全国重点实验室",
        brand_title_second_line="",
    ).update(
        brand_title="抗感染新药研发",
        brand_title_second_line="全国重点实验室",
        brand_subtitle="State Key Laboratory of Anti-infective Drug Discovery",
    )


def merge_existing_brand_title(apps, schema_editor):
    NavigationSettings = apps.get_model("navigation", "NavigationSettings")
    NavigationSettings.objects.filter(
        brand_title="抗感染新药研发",
        brand_title_second_line="全国重点实验室",
    ).update(
        brand_title="抗感染新药研发全国重点实验室",
        brand_title_second_line="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_navigationsettings_brand_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="brand_title_second_line",
            field=models.CharField(
                "Chinese brand title, second line",
                blank=True,
                default="",
                help_text="Second Chinese line shown next to the header logo.",
                max_length=120,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(split_existing_brand_title, merge_existing_brand_title),
    ]
