# Generated by Django 6.0.4 on 2026-04-20 09:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('navigation', '0003_navigationsettings_brand_title_second_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='brand_logo',
            field=models.ForeignKey(blank=True, help_text='页眉 Logo 图片；留空时使用内置 SKL 标识。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='页眉 Logo'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='brand_subtitle',
            field=models.CharField(blank=True, help_text='显示在 Logo 与中文标题下方的英文标题。', max_length=160, verbose_name='页眉英文标题'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='brand_title',
            field=models.CharField(blank=True, help_text='显示在页眉 Logo 右侧的中文第一行。', max_length=120, verbose_name='页眉中文标题第一行'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='brand_title_second_line',
            field=models.CharField(blank=True, help_text='显示在页眉 Logo 右侧的中文第二行。', max_length=120, verbose_name='页眉中文标题第二行'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='footer_navigation',
            field=wagtail.fields.StreamField([('link_section', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': '留空时使用页面的列表标题。', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('page', 1), ('title', 2)]], {}), 4: ('wagtail.blocks.URLBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('link', 4), ('title', 0)]], {}), 6: ('wagtail.blocks.StreamBlock', [[('internal', 3), ('external', 5)]], {'label': 'Links', 'max_num': None}), 7: ('wagtail.blocks.StructBlock', [[('section_heading', 0), ('links', 6)]], {})}, verbose_name='页脚导航'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='primary_navigation',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': '留空时使用页面的列表标题。', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('title', 1)]], {})}, help_text='网站顶部主导航。', verbose_name='主导航'),
        ),
    ]
