# Generated by Django 6.0.4 on 2026-05-19 05:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_alter_navigationsettings_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='partner_links',
            field=wagtail.fields.StreamField([('partner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '合作单位图标，前台将按固定尺寸居中裁剪。', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link', 0), ('title', 1), ('image', 2)]], {})}, help_text='显示在网站底部，可添加合作单位图标和外部链接。', verbose_name='合作单位'),
        ),
    ]
