# Generated by Django 6.0.4 on 2026-05-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articlepage_appear_in_search_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='open_source_directly',
            field=models.BooleanField(default=False, help_text='勾选后，新闻列表和首页新闻入口点击标题时直接打开原文链接。', verbose_name='列表中直接跳转原文'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='source_url',
            field=models.URLField(blank=True, help_text='外部来源地址，例如中山大学药学院官网或微信公众号原文。', verbose_name='原文链接'),
        ),
    ]
